#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          motor1,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motor2,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motor3,        tmotorNXT, PIDControl, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    RotateL,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    RotateR,              tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define THRESH 25 // variable to create a deadzone in the controller's y values
#define MINI 25  // variable for the minimum speed of drive motors in which robot moves
#define SCALE .78125 // variable that scales numbers between -128 and 128 to -100 and 100


task main()
{
	while(true)
	{
		getJoystickSettings(joystick);

		if (joy1Btn(3))
		{
			nxtDisplayCenteredTextLine(2,"Stage 1");
			servo [RotateL] = 206;
			servo [RotateR] = 50;
			wait1Msec(100);
				while(true)
				{
				if (joy1Btn(4))	{
					nxtDisplayCenteredTextLine(2,"Stage 2");
					break;
				}

				else {
					servo [RotateL] = 140;
					servo [RotateR] = 140;
				}

				else if (joy1Btn(5))	{
					servo [Rota

			}
		}
	}
}
