#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     IRSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          motor1,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motor2,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motor3,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorRD,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorRL,       tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorT,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorLD,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorLL,       tmotorTetrix, PIDControl)
#pragma config(Servo,  srvo_S1_C2_1,    RotateL,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    RotateR,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define THRESH 25 // variable to create a deadzone in the controller's y values
#define MINI 25  // variable for the minimum speed of drive motors in which robot moves
#define SCALE .78125 // variable that scales numbers between -128 and 128 to -100 and 100


task main()
{

	while(true)
	{
		getJoystickSettings(joystick);
		int reading = SensorValue[IRSensor];
		nxtDisplayCenteredTextLine(2, "Value: %s", SensorValue[IRSensor]);

		//if (joy1Btn(10)) // turns the crank
		//{
		//	motor[motorF] = -100 ;
		//}
		//else
		//{
		//	motor[motorF] = 0;
		//}

		if (joy1Btn(6)) // runs the grabber inwards
		{
			motor[motorT] = 100;
		}
		else if (joy1Btn(8)) // runs the grabber outwards
		{
			motor[motorT] = -100;
		}
		else
		{
			motor[motorT] =0;
		}

		if (joy1Btn(4)) // moves the robot foward at minimum speed
		{
			motor[motorLD] = -MINI;
			motor[motorRD]= MINI;
		}
		else if (joy1Btn(2)) // moves the robot backwards at minimum speed
		{
			motor[motorLD] = MINI;
			motor[motorRD] = -MINI;
		}
		else if (joy1Btn(1)) // rotates the robot in place clockwise
		{
			motor[motorLD] = MINI;
			motor[motorRD] = MINI;
		}
		else if (joy1Btn(3)) // rotates the robot in place counterclockwise
		{
			motor [motorLD] = -MINI;
			motor [motorRD] = -MINI;
		}
		else
		{
			if ((joystick.joy1_y1) > THRESH || (joystick.joy1_y1) < -THRESH) // runs the left side tread
			{
				motor[motorLD]= ((-joystick.joy1_y1)* SCALE);
			}
			else {
				motor[motorLD]= 0;
			}

			if ((joystick.joy1_y2) > THRESH || (joystick.joy1_y2) < -THRESH) // runs the right side tread
			{
				motor[motorRD]= ((joystick.joy1_y2)* SCALE);
			}
			else {
				motor[motorRD]= 0;
			}
		}

		if (joy1Btn(5)) // runs the lift up
		{
			motor [motorLL] = -75;
			motor [motorRL] = 75;
		}
		else if (joy1Btn(7)) // runs the lift down
		{
			motor [motorLL] = 75;
			motor [motorRL] = -75;
		}
		else{
			motor [motorLL] = 0;
			motor [motorRL] = 0;
		}

		if (joy1Btn(10)) // rotates the block holder towards dispensing position
		{
			servo [RotateL] = 206;
			servo [RotateR] = 50;
		}
		else if (joy1Btn(9)) // rotate the block holder towards gathering position
		{
			servo [RotateL] = 50;
			servo [RotateR] = 206;
		}
		else {
			servo [RotateL] = 127;
			servo [RotateR] = 127;
		}
	}
}
