#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          motor1,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motor2,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motor3,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define THRESH 10
#define SCALE .78125

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);

		if ((joystick.joy1_y1) > THRESH || (joystick.joy1_y1) < -THRESH)
			{
				motor[motorL]= (5*(pow(1.021872, -joystick.joy1_y1)));
			}
		else {
			motor[motorL]= 0;
					}


		if ((-joystick.joy1_y2) > THRESH || (-joystick.joy1_y2) < -THRESH)
			{
				motor[motorR]= ((joystick.joy1_y2)* SCALE);
			}
		else {
				motor[motorR]= 0;
					}
	}
}
